services:
  node-app:
    build: .  # Certifique-se de que o Dockerfile está na raiz do projeto
    ports:
      - "3000:8080"  # Expondo a porta 8080 do contêiner na porta 3000 da máquina host
    volumes:
      - .:/app  # Montando o diretório atual no contêiner
    depends_on:
      - mysql  # A aplicação Node.js depende do contêiner MySQL
    environment:
      - DB_HOST=mysql  # Nome do serviço MySQL
      - DB_USER=root
      - DB_PASSWORD=flamengo
      - DB_NAME=completa_ai

  mysql:
    image: mysql:8.0  # Usando a imagem MySQL 8.0
    environment:
      MYSQL_ROOT_PASSWORD: flamengo
      MYSQL_DATABASE: completa_ai
    volumes:
      - mysql-data:/var/lib/mysql  # Persistindo dados do MySQL
    ports:
      - "3307:3306"  # Expondo a porta 3306 do contêiner na porta 3307 da máquina host

volumes:
  mysql-data:  # Declarando um volume para persistência
