services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=emilly123
      - DB_NAME=completa_ai
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: emilly123
      MYSQL_DATABASE: completa_ai
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
