version: '3.8'
services:
  node-app:
    # Serviço para produção
    build:
      context: .
      dockerfile: Dockerfile # Usando Dockerfile para produção
    ports:
      - "3000:8080" # Mapeia a porta 8080 do contêiner para 3000 no host
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=flamengo
      - DB_NAME=completa_ai
    depends_on:
      - mysql
    volumes:
      - .:/app # Montar o diretório atual no contêiner
      - /app/node_modules # Adiciona um volume separado para node_modules

  node-app-dev:
    # Serviço para desenvolvimento
    build:
      context: .
      dockerfile: Dockerfile.dev # Usando Dockerfile.dev para desenvolvimento
    ports:
      - "3001:8080" # Mapeia a porta 8080 do contêiner para 3001 no host
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=flamengo
      - DB_NAME=completa_ai
    depends_on:
      - mysql
    volumes:
      - .:/app # Montar o diretório atual no contêiner
      - /app/node_modules # Adiciona um volume separado para node_modules

  mysql:
    # Serviço MySQL
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: flamengo
      MYSQL_DATABASE: completa_ai
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
